"""
Interactive experiment runner for the LLM IR Digital Twin.

This script builds and deploys the environment, clears old Snort
alerts, runs several client-side tests, reads alerts after each test,
and finally stops the digital twin.
"""
import logging
import time

from llm_ir_dt.constants.constants import DIGITAL_TWIN
from llm_ir_dt.docker_manager.docker_manager import DockerManager

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)8s] %(message)s "
           "(%(filename)s:%(lineno)s)",
)
logger = logging.getLogger(__name__)


TEST_CASES = [
    {
        "name": "Ping SSH server",
        "command": "ping -c 3 10.0.2.11",
    },
    {
        "name": "SYN scan SSH server",
        "command": "nmap -sS 10.0.2.11",
    },
    {
        "name": "SSH weak-password attempt",
        "command": "hydra -l root -p 123456 ssh://10.0.2.11",
    },
    {
        "name": "HTTP request to shellshock host",
        "command": "curl -i http://10.0.2.13/cgi-bin/test.cgi",
    },
]


def run_test_case(name: str, command: str) -> None:
    """
    Clear previous alerts, execute one client-side test, and read Snort
    alerts generated by that test.
    """
    logger.info("=== %s ===", name)

    clear_result = DockerManager.clear_alerts()
    logger.info("Clear alerts result: %s", clear_result)

    result = DockerManager.exec_run("client", command)
    logger.info("Command result: %s", result)

    # Give Snort a short window to flush alerts to disk.
    time.sleep(2)

    alerts = DockerManager.read_alerts()
    logger.info("Snort alerts: %s", alerts)


def main() -> None:
    """
    Run a full experiment cycle against the digital twin.
    """
    config = DIGITAL_TWIN.DEFAULT_CONFIG

    logger.info("Building Docker images...")
    build_result = DockerManager.build_images()
    if build_result["exit_code"] != 0:
        logger.error("Image build failed: %s", build_result["stderr"])
        return

    try:
        logger.info("Deploying digital twin...")
        for item in DockerManager.deploy(config):
            logger.info("Deploy: %s", item)

        logger.info("Waiting for services to initialize...")
        time.sleep(15)

        status = DockerManager.status(config)
        logger.info("Status: %s", status)
        logger.info(
            "Snort process: %s",
            DockerManager.exec_run("gateway", "ps aux | grep snort"),
        )
        logger.info(
            "Snort log dir: %s",
            DockerManager.exec_run("gateway", "ls -l /var/log/snort"),
        )
        logger.info(
            "Snort alert file: %s",
            DockerManager.exec_run("gateway", "cat /var/log/snort/alert"),
        )
        logger.info(
            "Gateway interfaces: %s",
            DockerManager.exec_run("gateway", "ip addr"),
        )
        logger.info(
            "Snort config test: %s",
            DockerManager.exec_run(
                "gateway",
                "snort -T -c /etc/snort/snort.conf",
            ),
        )

        for test_case in TEST_CASES:
            run_test_case(test_case["name"], test_case["command"])
    finally:
        logger.info("Stopping digital twin...")
        for item in DockerManager.stop():
            logger.info("Stop: %s", item)


if __name__ == "__main__":
    main()
