import argparse
import json
import random
import re
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import torch
from peft import PeftConfig, PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer

from llm_recovery.decision_transformer.planner import (
    IncidentResponsePlanner,
    PlannerConfig,
    RECOVERY_STATE_FIELDS,
    TERMINAL_STATE,
)

INCIDENT_PROMPT_TEMPLATE = """Below is a system description, a sequence of network logs (e.g., from an intrusion detection system), and an instruction that describes a task. Write a response that appropriately completes the request. Before generating the response, think carefully about the system, the logs, and the instruction, then create a step-by-step chain of thoughts to ensure a logical and accurate response.

### System:
{system}

### Logs:
{logs}

### Instruction:
You are a security operator with advanced knowledge in cybersecurity and IT systems. You have been given information about a system and some logs generated by it, e.g., security alerts. Your task is to determine if the logs indicate a cyber incident (i.e., attack) that requires recovery actions. If the logs are just indicative of normal system activity or if they are unrelated to security, then you should classify the logs/system as not being an incident that requires recovery. Similarly, if the logs contain very minor security alerts that do not warrant any recovery action, then you should classify the logs/system as not being an incident that requires recovery. If there is an incident that requires action, you should concisely describe the incident and explain why it is an incident, i.e., you should indicate which parts of the logs or system description indicate that there is an incident that requires immediate action. It is important that any conclusions you make in the incident description are supported by the logs/system description, dont make guesses. You should also associate the incident with tactics and techniques from the MITRE ATT&CK taxonomy. You should also identify entities involved in the incident. Return a JSON object with five fields: Incident, Incident description, MITRE ATT&CK Tactics, MITRE ATT&CK Techniques, and Entities. Incident should be a string that is either Yes or No. Incident description should be a string with a concise summary of the incident and explanation of why the logs/system description indicate that there is an incident. MITRE ATT&CK Tactics should be an array of strings, each of which corresponds to one tactic used by the attacker in the incident. MITRE ATT&CK Techniques should be an array of strings, each of which corresponds to one technique used by the attacker in the incident. Entities should be a JSON object with three properties: Attacker, System, and Targeted, where Attacker should be an array of strings, each of which is either an IP or a hostname that is related to the attacker/adversary, System should be an array of strings, each of which is either an IP or a hostname that corresponds to some component in the system, and Targeted should be an array of strings, each of which is either an IP or a hostname that corresponds to some component in the system that is under attack. If the Incident field is set to No, then Incident description should be No incident can be inferred from the logs because they contain no substantial information., MITRE ATT&CK Tactics should be an empty array, MITRE ATT&CK Techniques should be an empty array, and Entities should be an empty JSON object. Return only the JSON with the above five fields, nothing else.

### Response:
<think>"""


ACTION_PROMPT_TEMPLATE = (
    "Below is a system description, a sequence of network logs (e.g., from an intrusion detection system), "
    "a description of a cybersecurity incident, the current state of the recovery from the incident, "
    "a list of previously executed recovery actions, "
    "and an instruction that describes a task.\n"
    "Write a response that appropriately completes the request.\nBefore generating the response, "
    "think carefully about the system, the logs, and the instruction, then create a step-by-step "
    "chain of thoughts to ensure a logical and accurate response.\n\n"
    "### System:\n{}\n\n"
    "### Logs:\n{}\n\n"
    "### Incident:\n{}\n\n"
    "### State:\n{}\n"
    "The meaning of the state fields are as follows.\n"
    "is_attack_contained: Has the immediate threat been stopped from spreading?\n"
    "is_knowledge_sufficient: Have we gathered enough data to effectively contain and eradicate the attack?\n"
    "are_forensics_preserved: Has evidence been captured and stored in a forensically sound manner?\n"
    "is_eradicated: Is the adversary completely removed from the system?\n"
    "is_hardened: Has the root cause of the attack been remediated? i.e., are future attacks of the same "
    "type prevented?\n"
    "is_recovered: Are primary services restored for users?\n\n"
    "### Previous recovery actions:\n{}\n\n"
    "### Instruction:\n"
    "You are a security operator with advanced knowledge in cybersecurity "
    "and IT systems. You have been given information about a security incident and should"
    " generate the next suitable action for recovering the system from the incident. "
    "Your suggested action should be based on the logs, the system description only, the current state, and the "
    "previous recovery actions.\n"
    "Make sure that the suggested recovery action is consistent with the system description and the logs and that "
    "you do not repeat any action that has already been performed.\n"
    "The goal when selecting the recovery action is to change the state so that one of the state-properties that "
    "is currently 'false' "
    "becomes 'true'. The ideal recovery action sequence is: 1. contain the attack 2. gather information 3. "
    "preserve evidence "
    "4. eradicate the attacker 5. harden the system 6. recover operational services.\n"
    "When selecting the recovery action, make sure that it is concrete and actionable and minimizes unnecessary "
    "service disruptions. "
    "Vague or unnecessary actions will not change the state and should be avoided.\n"
    "Return a JSON object with two properties: 'Action' and 'Explanation', both of which should be strings.\n"
    "The property 'Action' should be a string that concisely describes the concrete recovery action.\n"
    "The property 'Explanation' should be a string that concisely explains why you selected the recovery action "
    "and motivates why the action is needed.\n\n"
    "### Response:\n<think>"
)

STATE_PROMPT_TEMPLATE = (
    "Below is a system description, a sequence of network logs (e.g., from an intrusion detection system), "
    "a description of a cybersecurity incident, the current state of the recovery from the incident, "
    "a proposed recovery action, and an instruction that describes a task.\n"
    "Write a response that appropriately completes the request.\nBefore generating the response, "
    "think carefully about the system, the logs, and the instruction, then create a step-by-step "
    "chain of thoughts to ensure a logical and accurate response.\n\n"
    "### System:\n{}\n\n"
    "### Logs:\n{}\n\n"
    "### Incident:\n{}\n\n"
    "### State:\n{}\n"
    "The meaning of the state fields are as follows.\n"
    "is_attack_contained: Has the immediate threat been stopped from spreading?\n"
    "is_knowledge_sufficient: Have we gathered enough data to effectively contain and eradicate the attack?\n"
    "are_forensics_preserved: Has evidence been captured and stored in a forensically sound manner?\n"
    "is_eradicated: Is the adversary completely removed from the system?\n"
    "is_hardened: Has the root cause of the attack been remediated? i.e., are future attacks of the same "
    "type prevented?\n"
    "is_recovered: Are primary services restored for users?\n\n"
    "### Recovery action:\n{}\n\n"
    "### Instruction:\n"
    "You are a security operator with advanced knowledge in cybersecurity "
    "and IT systems.\nYou have been given information about a security incident, the state of recovery from "
    "the incident, "
    "and a recovery action.\nYour task is to predict what the next state of the recovery will be after applying "
    "the recovery action.\n"
    "For example, if the given recovery action effectively contains the attack and 'is_attack_contained' is "
    "'false' in the "
    "current state, then the next state should have 'is_attack_contained' set to 'true'.\nSimilarly, if "
    "'is_recovered' is 'false' "
    "in the current state and the given recovery action effectively recovers operational services of the system,"
    " then the next state "
    "should have 'is_recovered' set to 'true', etc.\nIt is also possible that multiple state properties change "
    "values from false to true. "
    "It is also possible that the state remains the same, i.e., no property changes.\nIt is important that the "
    "state only changes if the "
    "action is effective in achieving one of the recovery goals: containment, information gathering, preserving "
    "evidence, eradication, "
    "hardening, or recovery.\nA state variable can only change from 'false' to 'true', it cannot be changed from "
    "'true' to 'false'.\n"
    "Return a JSON object that defines the next state and contains the Boolean fields 'is_attack_contained', "
    "'is_knowledge_sufficient', 'are_forensics_preserved', 'is_eradicated', 'is_hardened', 'is_recovered'.\n\n"
    "### Response:\n<think>"
)

def _format_state_json(state: Sequence[bool]) -> str:
    return json.dumps(
        {field: bool(state[i]) for i, field in enumerate(RECOVERY_STATE_FIELDS)},
        ensure_ascii=True,
    )


def build_action_prompt(
    context: Dict[str, str],
    state: Sequence[bool],
    previous_actions: Sequence[str],
) -> str:
    state_json = _format_state_json(state)
    if previous_actions:
        prev_actions = "\n".join(f"- {a}" for a in previous_actions).strip()
    else:
        prev_actions = "None."
    return ACTION_PROMPT_TEMPLATE.format(
        context.get("System", "").strip(),
        context.get("Logs", "").strip(),
        context.get("Incident", "").strip(),
        state_json,
        prev_actions,
    ).rstrip()


def build_state_prompt(
    context: Dict[str, str],
    state: Sequence[bool],
    action: str,
) -> str:
    state_json = _format_state_json(state)
    return STATE_PROMPT_TEMPLATE.format(
        context.get("System", "").strip(),
        context.get("Logs", "").strip(),
        context.get("Incident", "").strip(),
        state_json,
        action.strip(),
    ).rstrip()


 


def _start_label_object() -> Dict[str, object]:
    return {
        "System": "",
        "Logs": [],
        "Incident": "",
        "Incident description": "",
        "Recovery actions": [],
    }


def _normalize_label_key(key: str) -> str:
    if key == "system":
        return "System"
    return key


def _parse_labels_file(path: str) -> List[Dict[str, object]]:
    lines = Path(path).read_text(encoding="utf-8", errors="replace").splitlines()
    objects: List[Dict[str, object]] = []
    cur: Optional[Dict[str, object]] = None

    i = 0
    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        if stripped.startswith("{"):
            cur = _start_label_object()
            i += 1
            continue
        if stripped.startswith("}"):
            if cur is not None:
                objects.append(cur)
            cur = None
            i += 1
            continue
        if cur is None:
            i += 1
            continue

        if stripped.startswith('"') and ":" in stripped:
            key_part, rest = stripped.split(":", 1)
            key = _normalize_label_key(key_part.strip().strip('"'))
            rest = rest.strip()

            if key == "Logs":
                if "[" in rest:
                    i += 1
                    while i < len(lines):
                        item_line = lines[i].strip()
                        if item_line.startswith("]"):
                            break
                        if item_line.startswith('"'):
                            item = item_line.rstrip(",")
                            if item.startswith('"') and item.endswith('"'):
                                item = item[1:-1]
                            cur["Logs"].append(item)
                        i += 1
                    i += 1
                    continue

            if key == "Recovery actions":
                if rest.startswith("[]"):
                    cur["Recovery actions"] = []
                    i += 1
                    continue
                if rest.startswith("["):
                    i += 1
                    while i < len(lines):
                        item_line = lines[i].strip()
                        if item_line.startswith("]"):
                            break
                        if item_line.startswith('"'):
                            item = item_line.rstrip(",")
                            if item.startswith('"') and item.endswith('"'):
                                item = item[1:-1]
                            cur["Recovery actions"].append(item)
                        i += 1
                    i += 1
                    continue

            if rest.startswith('"'):
                if rest.count('"') >= 2 and rest.endswith('"'):
                    value = rest.rstrip(",")[1:-1]
                    cur[key] = value
                    i += 1
                    continue
                buf = [rest.lstrip('"')]
                i += 1
                while i < len(lines):
                    next_line = lines[i]
                    if next_line.strip().startswith('"') and ":" in next_line:
                        i -= 1
                        break
                    buf.append(next_line)
                    if next_line.rstrip().endswith('"'):
                        break
                    i += 1
                value = "\n".join(buf).rstrip(",")
                if value.endswith('"'):
                    value = value[:-1]
                cur[key] = value
                i += 1
                continue

        i += 1

    return objects


def _read_optional_text(path: Optional[str]) -> Optional[str]:
    if not path:
        return None
    return Path(path).read_text(encoding="utf-8").strip()


def _extract_final_json(text: str) -> Optional[dict[str, Any]]:
    decoder = json.JSONDecoder()
    matches = list(re.finditer(r"\{", text))
    for match in reversed(matches):
        candidate = text[match.start():]
        try:
            obj, _ = decoder.raw_decode(candidate)
        except json.JSONDecodeError:
            continue
        if isinstance(obj, dict) and "Incident" in obj and "Incident description" in obj:
            return obj
    return None


def _build_context_from_answer_files(
    system_text: str,
    logs_text: str,
    answer_text: str,
) -> Dict[str, str]:
    parsed = _extract_final_json(answer_text)
    if parsed is None:
        raise SystemExit("Could not extract final JSON object from --answer-file.")

    incident = str(parsed.get("Incident", "")).strip()
    incident_description = str(parsed.get("Incident description", "")).strip()
    if incident.lower() != "yes":
        raise SystemExit(
            f"Incident must be 'Yes' to run planning. Extracted value from --answer-file: {incident!r}"
        )
    if not incident_description:
        raise SystemExit("Incident description is empty in the JSON extracted from --answer-file.")

    return {
        "System": system_text.strip(),
        "Logs": _normalize_logs_text(logs_text),
        "Incident": incident_description,
    }


def _load_generation_model(
    model_path: str,
    torch_dtype: str,
) -> tuple[AutoTokenizer, AutoModelForCausalLM]:
    dtype = getattr(torch, torch_dtype)
    adapter_config = Path(model_path) / "adapter_config.json"
    if adapter_config.exists():
        adapter_meta = json.loads(adapter_config.read_text(encoding="utf-8"))
        base_model = adapter_meta.get("base_model_name_or_path")
        if not base_model:
            raise SystemExit("adapter_config.json missing base_model_name_or_path")
        tokenizer = AutoTokenizer.from_pretrained(base_model, use_fast=True)
        base = AutoModelForCausalLM.from_pretrained(
            base_model,
            device_map="auto",
            torch_dtype=dtype,
        )
        model = PeftModel.from_pretrained(base, model_path)
    else:
        tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=True)
        model = AutoModelForCausalLM.from_pretrained(
            model_path,
            device_map="auto",
            torch_dtype=dtype,
        )

    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    model.eval()
    return tokenizer, model


def _generate_text(
    model: AutoModelForCausalLM,
    tokenizer: AutoTokenizer,
    prompt: str,
    max_new_tokens: int,
    temperature: float,
    top_p: float,
) -> str:
    inputs = tokenizer(prompt, return_tensors="pt")
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=temperature > 0.0,
            temperature=temperature,
            top_p=top_p,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )

    full_text = tokenizer.decode(output_ids[0], skip_special_tokens=True)
    generated_text = full_text[len(prompt):] if full_text.startswith(prompt) else full_text
    return generated_text.strip()


def _build_context_via_incident_model(
    system_text: str,
    logs_text: str,
    incident_model_path: str,
    incident_torch_dtype: str,
    incident_max_new_tokens: int,
    incident_temperature: float,
    incident_top_p: float,
) -> tuple[Dict[str, str], str, dict[str, Any]]:
    prompt = INCIDENT_PROMPT_TEMPLATE.format(
        system=system_text.strip(),
        logs=_normalize_logs_text(logs_text),
    )
    tokenizer, model = _load_generation_model(
        model_path=incident_model_path,
        torch_dtype=incident_torch_dtype,
    )
    answer_text = _generate_text(
        model=model,
        tokenizer=tokenizer,
        prompt=prompt,
        max_new_tokens=incident_max_new_tokens,
        temperature=incident_temperature,
        top_p=incident_top_p,
    )
    parsed = _extract_final_json(answer_text)
    if parsed is None:
        raise SystemExit("Could not extract final JSON object from incident-model output.")

    incident = str(parsed.get("Incident", "")).strip()
    incident_description = str(parsed.get("Incident description", "")).strip()
    if incident.lower() != "yes":
        raise SystemExit(
            f"Incident model returned Incident={incident!r}. Planning runs only for Incident='Yes'."
        )
    if not incident_description:
        raise SystemExit("Incident model output JSON has an empty Incident description.")

    return (
        {
            "System": system_text.strip(),
            "Logs": _normalize_logs_text(logs_text),
            "Incident": incident_description,
        },
        answer_text,
        parsed,
    )


def _load_datapoint_file(path: str) -> Dict[str, str]:
    parsed = json.loads(Path(path).read_text(encoding="utf-8"))
    if not isinstance(parsed, dict):
        raise SystemExit("--datapoint-file must contain a JSON object.")

    system_text = str(parsed.get("System", "")).strip()
    incident_text = str(parsed.get("Incident description", "") or parsed.get("Incident", "")).strip()
    logs_value = parsed.get("Logs", [])

    if isinstance(logs_value, list):
        logs_text = "\n".join(str(item).strip() for item in logs_value if str(item).strip()).strip()
    else:
        logs_text = str(logs_value).strip()

    return {
        "System": system_text,
        "Logs": logs_text,
        "Incident": incident_text,
    }


def _normalize_logs_text(logs_text: str) -> str:
    text = logs_text.strip()
    if not text:
        return ""
    try:
        parsed = json.loads(text)
    except json.JSONDecodeError:
        return text

    if isinstance(parsed, list):
        return "\n".join(str(item).strip() for item in parsed if str(item).strip()).strip()
    return text


def _resolve_context(args: argparse.Namespace) -> Dict[str, str]:
    context: Dict[str, str] = {}
    if args.datapoint_file:
        context = _load_datapoint_file(args.datapoint_file)

    if args.labels:
        if args.labels_seed is not None:
            random.seed(args.labels_seed)
        labels = _parse_labels_file(args.labels)
        incident_yes = [
            obj
            for obj in labels
            if str(obj.get("Incident", "")).strip().lower() == "yes"
        ]
        if not incident_yes:
            raise SystemExit("No Incident=Yes entries found in labels.json")
        if args.labels_index is not None:
            idx = max(0, min(args.labels_index, len(incident_yes) - 1))
            sample = incident_yes[idx]
        else:
            sample = random.choice(incident_yes)
        context = {
            "System": str(sample.get("System", "")).strip(),
            "Logs": "\n".join(sample.get("Logs", [])).strip(),
            "Incident": str(sample.get("Incident description", "")).strip(),
        }

    system_text = args.system or _read_optional_text(args.system_file)
    logs_text = args.logs or _read_optional_text(args.logs_file)
    incident_text = args.incident or _read_optional_text(args.incident_file)
    answer_text = _read_optional_text(args.answer_file)
    incident_output_text = ""
    incident_output_json: Optional[dict[str, Any]] = None

    if args.incident_model:
        context, incident_output_text, incident_output_json = _build_context_via_incident_model(
            system_text=system_text or "",
            logs_text=logs_text or "",
            incident_model_path=args.incident_model,
            incident_torch_dtype=args.incident_torch_dtype,
            incident_max_new_tokens=args.incident_max_new_tokens,
            incident_temperature=args.incident_temperature,
            incident_top_p=args.incident_top_p,
        )
    elif answer_text is not None:
        context = _build_context_from_answer_files(
            system_text or "",
            logs_text or "",
            answer_text,
        )

    if not context and (system_text is not None or logs_text is not None or incident_text is not None):
        context = {
            "System": (system_text or "").strip(),
            "Logs": _normalize_logs_text(logs_text or ""),
            "Incident": (incident_text or "").strip(),
        }

    if incident_output_text:
        print("\n=== Incident Model Output ===")
        print(incident_output_text)
        print("\n=== Extracted Incident JSON ===")
        print(json.dumps(incident_output_json, ensure_ascii=False, indent=2))
        print("\n=== Incident Description Used For Planning ===")
        print(context.get("Incident", ""))

    return context


def build_planner(
    adapter_path: str,
    base_model: Optional[str],
    device_map: str,
    torch_dtype: str,
    config: PlannerConfig,
    context: Dict[str, str],
) -> Tuple[IncidentResponsePlanner, List[str]]:
    peft_cfg = PeftConfig.from_pretrained(adapter_path)
    base_name = base_model or peft_cfg.base_model_name_or_path
    dtype = getattr(torch, torch_dtype)

    tokenizer = AutoTokenizer.from_pretrained(base_name, use_fast=True)
    base = AutoModelForCausalLM.from_pretrained(
        base_name,
        device_map=device_map,
        torch_dtype=dtype,
    )
    model = PeftModel.from_pretrained(base, adapter_path)

    history: List[str] = []
    action_builder = lambda logs, state: build_action_prompt(
        context, state, history
    )
    state_builder = lambda logs, state, action: build_state_prompt(
        context, state, action
    )
    planner = IncidentResponsePlanner(
        model,
        tokenizer,
        config=config,
        action_prompt_builder=action_builder,
        state_prompt_builder=state_builder,
    )
    return planner, history


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Simulate the planning algorithm using a LoRA fine-tuned LLM."
    )
    parser.add_argument(
        "--adapter",
        required=False,
        default=None,
        help="Path to the LoRA adapter checkpoint directory.",
    )
    parser.add_argument(
        "--base-model",
        default=None,
        help="Base model name/path (optional; inferred from LoRA config if omitted).",
    )
    parser.add_argument(
        "--labels",
        default=None,
        help="Optional labels.json path; if provided, sample Incident=Yes from it.",
    )
    parser.add_argument(
        "--datapoint-file",
        default=None,
        help="Optional path to a planning data point JSON file with System, Logs, and Incident description.",
    )
    parser.add_argument(
        "--incident-model",
        default=None,
        help=(
            "Optional path to the incident-understanding model or LoRA checkpoint. "
            "When set with --system-file/--logs-file, the script first runs incident inference and then planning."
        ),
    )
    parser.add_argument(
        "--system-file",
        default=None,
        help="Optional path to a text file containing the System section.",
    )
    parser.add_argument(
        "--logs-file",
        default=None,
        help="Optional path to a text or JSON file containing the Logs section.",
    )
    parser.add_argument(
        "--incident-file",
        default=None,
        help="Optional path to a text file containing the Incident description section.",
    )
    parser.add_argument(
        "--answer-file",
        default=None,
        help=(
            "Optional path to an incident-model output text file. "
            "When set together with --system-file/--logs-file, and --incident-model is not used, the script extracts the final JSON "
            "and uses its Incident description for planning."
        ),
    )
    parser.add_argument(
        "--incident-max-new-tokens",
        type=int,
        default=1024,
        help="Maximum new tokens for the incident-model generation step.",
    )
    parser.add_argument(
        "--incident-temperature",
        type=float,
        default=0.0,
        help="Sampling temperature for the incident-model generation step.",
    )
    parser.add_argument(
        "--incident-top-p",
        type=float,
        default=1.0,
        help="Top-p for the incident-model generation step.",
    )
    parser.add_argument(
        "--incident-torch-dtype",
        choices=("float16", "bfloat16"),
        default="float16",
        help="Torch dtype used when loading the incident model.",
    )
    parser.add_argument(
        "--system",
        default=None,
        help="Optional inline System text. Overrides --system-file.",
    )
    parser.add_argument(
        "--logs",
        default=None,
        help="Optional inline Logs text. Overrides --logs-file.",
    )
    parser.add_argument(
        "--incident",
        default=None,
        help="Optional inline Incident description. Overrides --incident-file.",
    )
    parser.add_argument(
        "--labels-seed",
        type=int,
        default=None,
        help="Random seed for labels.json sampling.",
    )
    parser.add_argument(
        "--labels-index",
        type=int,
        default=None,
        help="Optional index for Incident=Yes entries (overrides random sampling).",
    )
    parser.add_argument(
        "--print-selected-sample",
        action="store_true",
        help="Print selected System/Logs/Incident description and exit.",
    )
    parser.add_argument("--num-candidates", type=int, default=3)
    parser.add_argument("--num-rollouts", type=int, default=3)
    parser.add_argument("--max-plan-steps", type=int, default=10)
    parser.add_argument("--max-rollout-depth", type=int, default=10)
    parser.add_argument("--max-new-tokens", type=int, default=500)
    parser.add_argument("--temperature", type=float, default=0.6)
    parser.add_argument("--top-p", type=float, default=0.9)
    parser.add_argument("--device-map", default="auto")
    parser.add_argument("--torch-dtype", default="float16")
    parser.add_argument(
        "--show-progress",
        action="store_true",
        help="Print per-step planning progress and rollout scores.",
    )
    parser.add_argument(
        "--show-rollout-progress",
        action="store_true",
        help="Print per-rollout progress for each candidate action.",
    )
    args = parser.parse_args()

    context = _resolve_context(args)
    if not context:
        raise SystemExit(
            "No context provided. Pass --datapoint-file, --labels, or provide --system-file/--logs-file with --incident-model, or --system-file/--logs-file with --answer-file, or --system-file/--logs-file/--incident-file."
        )
    if args.print_selected_sample:
        print("Selected sample (Incident=Yes):")
        print("\n### System:\n" + context.get("System", ""))
        print("\n### Logs:\n" + context.get("Logs", ""))
        print("\n### Incident description:\n" + context.get("Incident", ""))
        return
    if not args.adapter:
        raise SystemExit("--adapter is required unless --print-selected-sample is used.")

    config = PlannerConfig(
        num_candidates=args.num_candidates,
        num_rollout_samples=args.num_rollouts,
        max_plan_steps=args.max_plan_steps,
        max_rollout_depth=args.max_rollout_depth,
        action_max_new_tokens=args.max_new_tokens,
        state_max_new_tokens=args.max_new_tokens,
        candidate_temperature=args.temperature,
        candidate_top_p=args.top_p,
        rollout_temperature=args.temperature,
        rollout_top_p=args.top_p,
    )

    planner, history = build_planner(
        adapter_path=args.adapter,
        base_model=args.base_model,
        device_map=args.device_map,
        torch_dtype=args.torch_dtype,
        config=config,
        context=context,
    )

    state: Tuple[bool, ...] = tuple(False for _ in RECOVERY_STATE_FIELDS)
    plan: List[str] = []
    t = 0

    while state != TERMINAL_STATE and t < config.max_plan_steps:
        if args.show_progress:
            print(f"\n[Step {t+1}] Current state: {state}")
        actions = planner._sample_actions("", state, config.num_candidates)
        if not actions:
            break
        scores = []
        for idx_action, action in enumerate(actions, start=1):
            if args.show_rollout_progress:
                print(f"  Rollouts for candidate {idx_action}/{len(actions)}")
            samples = []
            for r in range(config.num_rollout_samples):
                if args.show_rollout_progress:
                    print(f"    rollout {r+1}/{config.num_rollout_samples}")
                samples.append(planner._recovery_time("", state, action, depth=0))
            score = float(sum(samples)) / float(len(samples))
            scores.append(score)
        best_idx = min(range(len(actions)), key=lambda i: scores[i])
        best_action = actions[best_idx]
        if args.show_progress:
            for i, (a, s) in enumerate(zip(actions, scores), start=1):
                print(f"  Candidate {i}: score={s:.3f} action={a}")
            print(f"  चुosen action: {best_action}")
        plan.append(best_action)
        history.append(best_action)

        next_state = planner._predict_state("", state, best_action)
        if next_state is None:
            break
        if args.show_progress:
            print(f"  Next state: {next_state}")
        state = next_state
        t += 1
    print("Generated plan:")
    for idx, action in enumerate(plan, start=1):
        print(f"{idx}. {action}")
    print("\nFinal state:")
    print(
        json.dumps(
            {field: bool(state[i]) for i, field in enumerate(RECOVERY_STATE_FIELDS)},
            ensure_ascii=True,
            indent=2,
        )
    )
    if state == TERMINAL_STATE:
        print("\nReached terminal state (all ones).")
    else:
        print(f"\nStopped at step {t} before reaching terminal state.")


if __name__ == "__main__":
    main()
