from __future__ import annotations

import argparse
import json
import random
import re
from collections import Counter
from pathlib import Path
from typing import Any

import torch
from datasets import load_dataset
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer


DEFAULT_PROMPT = """Below is a system description, a sequence of network logs (e.g., from an intrusion detection system), and an instruction that describes a task. Write a response that appropriately completes the request. Before generating the response, think carefully about the system, the logs, and the instruction, then create a step-by-step chain of thoughts to ensure a logical and accurate response.

### System:
...

### Logs:
...

### Instruction:
You are a security operator with advanced knowledge in cybersecurity and IT systems. You have been given information about a system and some logs generated by it, e.g., security alerts. Your task is to determine if the logs indicate a cyber incident (i.e., attack) that requires recovery actions. If the logs are just indicative of normal system activity or if they are unrelated to security, then you should classify the logs/system as not being an incident that requires recovery. Similarly, if the logs contain very minor security alerts that do not warrant any recovery action, then you should classify the logs/system as not being an incident that requires recovery. If there is an incident that requires action, you should concisely describe the incident and explain why it is an incident, i.e., you should indicate which parts of the logs or system description indicate an incident that requires immediate action. It is important that any conclusions you make in the incident description are supported by the logs/system description, dont make guesses. You should also associate the incident with tactics and techniques from the MITRE ATT&CK taxonomy. You should also identify entities involved in the incident. Return a JSON object with five fields: Incident, Incident description, MITRE ATT&CK Tactics, MITRE ATT&CK Techniques, and Entities. Incident should be a string that is either Yes or No. Incident description should be a string with a concise summary of the incident and explanation of why the logs/system description indicate that there is an incident. MITRE ATT&CK Tactics should be an array of strings, each of which corresponds to one tactic used by the attacker in the incident. MITRE ATT&CK Techniques should be an array of strings, each of which corresponds to one technique used by the attacker in the incident. Entities should be a JSON object with three properties: Attacker, System, and Targeted, where Attacker should be an array of strings, each of which is either an IP or a hostname that is related to the attacker/adversary, System should be an array of strings, each of which is either an IP or a hostname that corresponds to some component in the system, and Targeted should be an array of strings, each of which is either an IP or a hostname that corresponds to some component in the system that is under attack. If the Incident field is set to No, then Incident description should be No incident can be inferred from the logs because they contain no substantial information., MITRE ATT&CK Tactics should be an empty array, MITRE ATT&CK Techniques should be an empty array, and Entities should be an empty JSON object. Return only the JSON with the above five fields, nothing else.

### Response:
<think>"""


PROMPT_TEMPLATE = """Below is a system description, a sequence of network logs (e.g., from an intrusion detection system), and an instruction that describes a task. Write a response that appropriately completes the request. Before generating the response, think carefully about the system, the logs, and the instruction, then create a step-by-step chain of thoughts to ensure a logical and accurate response.

### System:
{system}

### Logs:
{logs}

### Instruction:
You are a security operator with advanced knowledge in cybersecurity and IT systems. You have been given information about a system and some logs generated by it, e.g., security alerts. Your task is to determine if the logs indicate a cyber incident (i.e., attack) that requires recovery actions. If the logs are just indicative of normal system activity or if they are unrelated to security, then you should classify the logs/system as not being an incident that requires recovery. Similarly, if the logs contain very minor security alerts that do not warrant any recovery action, then you should classify the logs/system as not being an incident that requires recovery. If there is an incident that requires action, you should concisely describe the incident and explain why it is an incident, i.e., you should indicate which parts of the logs or system description indicate an incident that requires immediate action. It is important that any conclusions you make in the incident description are supported by the logs/system description, dont make guesses. You should also associate the incident with tactics and techniques from the MITRE ATT&CK taxonomy. You should also identify entities involved in the incident. Return a JSON object with five fields: Incident, Incident description, MITRE ATT&CK Tactics, MITRE ATT&CK Techniques, and Entities. Incident should be a string that is either Yes or No. Incident description should be a string with a concise summary of the incident and explanation of why the logs/system description indicate that there is an incident. MITRE ATT&CK Tactics should be an array of strings, each of which corresponds to one tactic used by the attacker in the incident. MITRE ATT&CK Techniques should be an array of strings, each of which corresponds to one technique used by the attacker in the incident. Entities should be a JSON object with three properties: Attacker, System, and Targeted, where Attacker should be an array of strings, each of which is either an IP or a hostname that is related to the attacker/adversary, System should be an array of strings, each of which is either an IP or a hostname that corresponds to some component in the system, and Targeted should be an array of strings, each of which is either an IP or a hostname that corresponds to some component in the system that is under attack. If the Incident field is set to No, then Incident description should be No incident can be inferred from the logs because they contain no substantial information., MITRE ATT&CK Tactics should be an empty array, MITRE ATT&CK Techniques should be an empty array, and Entities should be an empty JSON object. Return only the JSON with the above five fields, nothing else.

### Response:
<think>"""


ATTACK_TACTIC_ORDER = [
    "Reconnaissance",
    "Resource Development",
    "Initial Access",
    "Execution",
    "Persistence",
    "Privilege Escalation",
    "Defense Evasion",
    "Credential Access",
    "Discovery",
    "Lateral Movement",
    "Collection",
    "Command and Control",
    "Exfiltration",
    "Impact",
]

TACTIC_ORDER_INDEX = {
    tactic: idx for idx, tactic in enumerate(ATTACK_TACTIC_ORDER)
}

TACTIC_ID_TO_NAME = {
    "TA0043": "Reconnaissance",
    "TA0042": "Resource Development",
    "TA0001": "Initial Access",
    "TA0002": "Execution",
    "TA0003": "Persistence",
    "TA0004": "Privilege Escalation",
    "TA0005": "Defense Evasion",
    "TA0006": "Credential Access",
    "TA0007": "Discovery",
    "TA0008": "Lateral Movement",
    "TA0009": "Collection",
    "TA0011": "Command and Control",
    "TA0010": "Exfiltration",
    "TA0040": "Impact",
}

TACTIC_TEXT_ALIASES = {
    "reconnaissance": "Reconnaissance",
    "resource development": "Resource Development",
    "initial access": "Initial Access",
    "initial_access": "Initial Access",
    "execution": "Execution",
    "persistence": "Persistence",
    "privilege escalation": "Privilege Escalation",
    "defense evasion": "Defense Evasion",
    "defense_evasion": "Defense Evasion",
    "credential access": "Credential Access",
    "discovery": "Discovery",
    "lateral movement": "Lateral Movement",
    "collection": "Collection",
    "command and control": "Command and Control",
    "command_and_control": "Command and Control",
    "command and control c2": "Command and Control",
    "exfiltration": "Exfiltration",
    "impact": "Impact",
}


def load_model_and_tokenizer(
    model_path: str, dtype: torch.dtype
) -> tuple[AutoTokenizer, AutoModelForCausalLM]:
    adapter_config = Path(model_path) / "adapter_config.json"
    if adapter_config.exists():
        with adapter_config.open("r", encoding="utf-8") as f:
            adapter_meta = json.load(f)
        base_model = adapter_meta.get("base_model_name_or_path")
        if not base_model:
            raise ValueError("adapter_config.json missing base_model_name_or_path")
        tokenizer = AutoTokenizer.from_pretrained(base_model, use_fast=True)
        base = AutoModelForCausalLM.from_pretrained(
            base_model,
            device_map="auto",
            torch_dtype=dtype,
        )
        model = PeftModel.from_pretrained(base, model_path)
    else:
        tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=True)
        model = AutoModelForCausalLM.from_pretrained(
            model_path,
            device_map="auto",
            torch_dtype=dtype,
        )

    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    model.eval()
    return tokenizer, model


def extract_section(text: str, section_name: str, next_sections: list[str]) -> str:
    pattern = rf"### {re.escape(section_name)}:\s*(.*?)(?=\n### (?:{'|'.join(re.escape(s) for s in next_sections)}):|\Z)"
    match = re.search(pattern, text, flags=re.DOTALL)
    if not match:
        raise ValueError(
            f"Could not extract section '{section_name}' from dataset instruction"
        )
    return match.group(1).strip()


def rebuild_prompt_from_instruction(instruction: str) -> str:
    system_text = extract_section(
        instruction, "System", ["Logs", "Instruction", "Response"]
    )
    logs_text = extract_section(instruction, "Logs", ["Instruction", "Response"])
    return PROMPT_TEMPLATE.format(system=system_text, logs=logs_text)


def resolve_prompt(args: argparse.Namespace) -> str:
    if args.dataset:
        ds = load_dataset(args.dataset_repo, data_files=args.dataset)
        sample = ds["train"][0]
        instructions = sample["instructions"]
        if not isinstance(instructions, list) or not instructions:
            raise ValueError("Dataset does not contain a non-empty 'instructions' list")

        if args.random_sample:
            idx = random.randrange(len(instructions))
        else:
            idx = args.sample_index

        if idx < 0 or idx >= len(instructions):
            raise IndexError(
                f"sample index {idx} out of range for dataset with {len(instructions)} instructions"
            )
        print(f"Using dataset sample index: {idx}")
        instruction = instructions[idx]
        if args.use_original_dataset_prompt:
            return instruction
        return rebuild_prompt_from_instruction(instruction)
    if args.prompt_file:
        return Path(args.prompt_file).read_text(encoding="utf-8")
    if args.prompt:
        return args.prompt
    return DEFAULT_PROMPT


def resolve_dataset_answer(args: argparse.Namespace) -> str | None:
    if not args.dataset:
        return None
    ds = load_dataset(args.dataset_repo, data_files=args.dataset)
    sample = ds["train"][0]
    instructions = sample["instructions"]
    answers = sample["answers"]
    if not isinstance(instructions, list) or not instructions:
        raise ValueError("Dataset does not contain a non-empty 'instructions' list")
    if not isinstance(answers, list) or not answers:
        raise ValueError("Dataset does not contain a non-empty 'answers' list")

    if args.random_sample:
        random.seed(args.seed)
        idx = random.randrange(len(instructions))
    else:
        idx = args.sample_index

    if idx < 0 or idx >= len(instructions) or idx >= len(answers):
        raise IndexError(
            f"sample index {idx} out of range for dataset with "
            f"{len(instructions)} instructions and {len(answers)} answers"
        )
    return str(answers[idx])


def extract_json_object(text: str) -> dict[str, Any] | None:
    decoder = json.JSONDecoder()
    for match in re.finditer(r"\{", text):
        start = match.start()
        try:
            obj, _ = decoder.raw_decode(text[start:])
        except json.JSONDecodeError:
            continue
        if isinstance(obj, dict):
            return obj
    return None


def canonicalize_tactic(raw_tactic: Any) -> str | None:
    raw = str(raw_tactic).strip()
    if not raw:
        return None

    tactic_id_match = re.search(r"\bTA\d{4}\b", raw, flags=re.IGNORECASE)
    if tactic_id_match:
        tactic_id = tactic_id_match.group(0).upper()
        if tactic_id in TACTIC_ID_TO_NAME:
            return TACTIC_ID_TO_NAME[tactic_id]

    lowered = raw.lower().replace("&", "and")
    lowered = re.sub(r"[\(\)\[\]\{\}:,/-]+", " ", lowered)
    lowered = re.sub(r"\s+", " ", lowered).strip()
    if lowered in TACTIC_TEXT_ALIASES:
        return TACTIC_TEXT_ALIASES[lowered]

    compact = lowered.replace(" ", "_")
    if compact in TACTIC_TEXT_ALIASES:
        return TACTIC_TEXT_ALIASES[compact]

    for alias, canonical in TACTIC_TEXT_ALIASES.items():
        alias_tokens = alias.replace("_", " ")
        if re.search(rf"\b{re.escape(alias_tokens)}\b", lowered):
            return canonical

    return None


def sort_tactics_in_attack_order(tactics: list[str]) -> list[str]:
    return sorted(
        tactics,
        key=lambda tactic: (TACTIC_ORDER_INDEX.get(tactic, len(ATTACK_TACTIC_ORDER)), tactic),
    )


def normalize_tactics(obj: dict[str, Any]) -> list[str]:
    tactics = obj.get("MITRE ATT&CK Tactics", [])
    if not isinstance(tactics, list):
        return []
    seen: set[str] = set()
    normalized: list[str] = []
    for item in tactics:
        tactic = canonicalize_tactic(item)
        if tactic and tactic not in seen:
            seen.add(tactic)
            normalized.append(tactic)
    return sort_tactics_in_attack_order(normalized)


def generate_once(
    *,
    model: AutoModelForCausalLM,
    tokenizer: AutoTokenizer,
    prompt: str,
    max_new_tokens: int,
    temperature: float,
    top_p: float,
) -> str:
    inputs = tokenizer(prompt, return_tensors="pt")
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=temperature > 0.0,
            temperature=temperature,
            top_p=top_p,
            pad_token_id=tokenizer.pad_token_id,
        )

    full_text = tokenizer.decode(output_ids[0], skip_special_tokens=True)
    generated_text = full_text[len(prompt):] if full_text.startswith(prompt) else full_text
    return generated_text.strip()


def summarize_tactics(tactic_runs: list[list[str]]) -> list[dict[str, Any]]:
    counts: Counter[str] = Counter()
    total_runs = len(tactic_runs)
    for tactics in tactic_runs:
        for tactic in tactics:
            counts[tactic] += 1

    summary: list[dict[str, Any]] = []
    for tactic, count in sorted(
        counts.items(),
        key=lambda item: (
            -item[1],
            TACTIC_ORDER_INDEX.get(item[0], len(ATTACK_TACTIC_ORDER)),
            item[0],
        ),
    ):
        summary.append(
            {
                "tactic": tactic,
                "count": count,
                "ratio": count / total_runs if total_runs else 0.0,
            }
        )
    return summary


def infer_expected_tactic_count(answer_text: str | None) -> int | None:
    if not answer_text:
        return None
    parsed = extract_json_object(answer_text)
    if parsed is None:
        return None
    tactics = normalize_tactics(parsed)
    if not tactics:
        return None
    return len(tactics)


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Run a saved checkpoint against the original incident prompt and "
            "summarize MITRE ATT&CK tactics across repeated generations."
        )
    )
    parser.add_argument(
        "--model",
        required=True,
        help="Path to a LoRA checkpoint directory or a full model directory.",
    )
    parser.add_argument(
        "--dataset",
        default=None,
        help="Optional HF dataset data_files value, e.g. incident_examples.json.",
    )
    parser.add_argument(
        "--dataset-repo",
        default="kimhammar/CSLE-IncidentResponse-V1",
        help="HF dataset repo id used together with --dataset.",
    )
    parser.add_argument(
        "--sample-index",
        type=int,
        default=0,
        help="Instruction index to read from the dataset when --dataset is set.",
    )
    parser.add_argument(
        "--random-sample",
        action="store_true",
        help="Randomly choose one instruction from the dataset when --dataset is set.",
    )
    parser.add_argument(
        "--use-original-dataset-prompt",
        action="store_true",
        help="Use the dataset instruction exactly as stored instead of rebuilding it with the old template.",
    )
    parser.add_argument(
        "--prompt-file",
        default=None,
        help="Optional path to a text file containing the full prompt.",
    )
    parser.add_argument(
        "--prompt",
        default=None,
        help="Optional inline prompt string. Ignored if --prompt-file is provided.",
    )
    parser.add_argument("--max-new-tokens", type=int, default=1024)
    parser.add_argument("--temperature", type=float, default=0.7)
    parser.add_argument("--top-p", type=float, default=1.0)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--num-runs",
        type=int,
        default=10,
        help="Number of repeated generations for the same prompt.",
    )
    parser.add_argument(
        "--dtype",
        choices=("float16", "bfloat16"),
        default="float16",
        help="Model loading dtype.",
    )
    args = parser.parse_args()

    dtype = torch.float16 if args.dtype == "float16" else torch.bfloat16
    random.seed(args.seed)
    torch.manual_seed(args.seed)
    prompt = resolve_prompt(args)
    dataset_answer = resolve_dataset_answer(args)
    tokenizer, model = load_model_and_tokenizer(args.model, dtype=dtype)

    all_outputs: list[dict[str, Any]] = []
    tactic_runs: list[list[str]] = []

    for run_idx in range(args.num_runs):
        generated_text = generate_once(
            model=model,
            tokenizer=tokenizer,
            prompt=prompt,
            max_new_tokens=args.max_new_tokens,
            temperature=args.temperature,
            top_p=args.top_p,
        )
        parsed = extract_json_object(generated_text)
        tactics = normalize_tactics(parsed) if parsed is not None else []
        tactic_runs.append(tactics)
        all_outputs.append(
            {
                "run": run_idx + 1,
                "raw_output": generated_text,
                "parsed_json": parsed,
                "tactics": tactics,
            }
        )

    summary = summarize_tactics(tactic_runs)
    expected_tactic_count = infer_expected_tactic_count(dataset_answer)
    if expected_tactic_count is None:
        expected_tactic_count = 2
    top_tactics = [item["tactic"] for item in summary[:expected_tactic_count]]

    result = {
        "prompt": prompt,
        "num_runs": args.num_runs,
        "dataset_answer": dataset_answer,
        "expected_tactic_count": expected_tactic_count,
        "outputs": all_outputs,
        "tactic_summary": summary,
        "MITRE ATT&CK Tactics": top_tactics,
    }

    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
