from __future__ import annotations

import argparse
import json
import random
import re
from pathlib import Path

import torch
from datasets import load_dataset
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer


DEFAULT_PROMPT = """Below is a system description, a sequence of network logs (e.g., from an intrusion detection system), and an instruction that describes a task.
Write a response that appropriately completes the request.
Before generating the response, think carefully about the system, the logs, and the instruction, then create a step-by-step chain of thoughts to ensure a logical and accurate response.

### System:
...

### Logs:
...

### Instruction:
You are a security operator with advanced knowledge in cybersecurity and IT systems.
You have been given information about a system and some logs generated by it, e.g., security alerts.

Your task is to determine if the logs indicate a cyber incident (i.e., attack) that requires recovery actions.
If the logs are just indicative of normal system activity or if they are unrelated to security, then you should classify the logs/system as not being an incident that requires recovery.
Similarly, if the logs contain very minor security alerts that do not warrant any recovery action, then you should classify the logs/system as not being an incident that requires recovery.

If there is an incident that requires action, you should concisely describe the incident and explain why it is an incident, i.e., you should indicate which parts of the logs or system description indicate an incident that requires immediate action.
It is important that any conclusions you make in the incident description are supported by the logs/system description; do not make guesses.

You should also associate the incident with tactics and techniques from the MITRE ATT&CK taxonomy.
Return multiple plausible MITRE ATT&CK tactic chains that explain the attack whenever the logs support more than one reasonable attack progression.
Each tactic chain should represent one coherent possible attack progression supported by the available evidence.
The tactic chains should differ in a meaningful way, such as attacker objective, ordering of tactics, or whether lateral movement occurred, and not merely by dropping one tactic from another chain.
For each tactic chain, assign a probability between 0 and 1 representing how likely that chain is relative to the other returned chains.

Only include tactic chains that are supported by the logs and system description.
Do not invent unsupported attacker behavior.
For incident cases, prefer returning 2 to 3 tactic chains when there is credible ambiguity in the attack progression.
Return a single tactic chain with probability 1.0 only when alternative chains would be speculative or unsupported.

You should also identify entities involved in the incident.

Return a JSON object with five fields:
'Incident',
'Incident description',
'MITRE ATT&CK Tactic Chains',
'MITRE ATT&CK Techniques',
and 'Entities'.

'Incident' should be a string that is either 'Yes' or 'No'.

'Incident description' should be a string with a concise summary of the incident and explanation of why the logs/system description indicate that there is an incident.

'MITRE ATT&CK Tactic Chains' should be an array of JSON objects.
Each object should contain exactly two fields:
- 'chain': an array of strings, where each string is a MITRE ATT&CK tactic
- 'probability': a number between 0 and 1

Return up to 3 of the most plausible tactic chains supported by the logs and system description.
Return at least 2 tactic-chain objects whenever the evidence supports multiple plausible interpretations of the attack progression.
Sort the tactic chains by probability in descending order.
The probabilities should sum to 1 across all returned tactic chains.
Each item in 'MITRE ATT&CK Tactic Chains' must be an object with exactly two keys:
- 'chain'
- 'probability'
Do not output 'MITRE ATT&CK Tactic Chains' as an array of strings.
Do not output a single flat list of tactics.
Return exactly one tactic-chain object only when the evidence clearly supports just one non-speculative progression.

'MITRE ATT&CK Techniques' should be an array of strings, each of which corresponds to one technique used by the attacker in the incident.

'Entities' should be a JSON object with three properties:
'Attacker',
'System',
and 'Targeted'.

'Attacker' should be an array of strings, each of which is either an IP or a hostname that is related to the attacker/adversary.
'System' should be an array of strings, each of which is either an IP or a hostname that corresponds to some component in the system.
'Targeted' should be an array of strings, each of which is either an IP or a hostname that corresponds to some component in the system that is under attack.

If the 'Incident' field is set to 'No', then:
- 'Incident description' should be 'No incident can be inferred from the logs because they contain no substantial information.'
- 'MITRE ATT&CK Tactic Chains' should be an empty array
- 'MITRE ATT&CK Techniques' should be an empty array
- 'Entities' should be an empty JSON object

Example output format:
{{
  "Incident": "Yes",
  "Incident description": "Example incident summary.",
  "MITRE ATT&CK Tactic Chains": [
    {{
      "chain": ["Credential Access", "Initial Access"],
      "probability": 0.72
    }},
    {{
      "chain": ["Credential Access"],
      "probability": 0.28
    }}
  ],
  "MITRE ATT&CK Techniques": [
    "T1110.001 Brute Force: Password Guessing"
  ],
  "Entities": {{
    "Attacker": ["192.168.5.44"],
    "System": ["10.0.30.10", "ad01.hospital.local"],
    "Targeted": ["10.0.30.10", "ad01.hospital.local"]
  }}
}}

Return only the JSON with the above five fields, nothing else.

### Response:
<think>"""


PROMPT_TEMPLATE = """Below is a system description, a sequence of network logs (e.g., from an intrusion detection system), and an instruction that describes a task.
Write a response that appropriately completes the request.
Before generating the response, think carefully about the system, the logs, and the instruction, then create a step-by-step chain of thoughts to ensure a logical and accurate response.

### System:
{system}

### Logs:
{logs}

### Instruction:
You are a security operator with advanced knowledge in cybersecurity and IT systems.
You have been given information about a system and some logs generated by it, e.g., security alerts.

Your task is to determine if the logs indicate a cyber incident (i.e., attack) that requires recovery actions.
If the logs are just indicative of normal system activity or if they are unrelated to security, then you should classify the logs/system as not being an incident that requires recovery.
Similarly, if the logs contain very minor security alerts that do not warrant any recovery action, then you should classify the logs/system as not being an incident that requires recovery.

If there is an incident that requires action, you should concisely describe the incident and explain why it is an incident, i.e., you should indicate which parts of the logs or system description indicate an incident that requires immediate action.
It is important that any conclusions you make in the incident description are supported by the logs/system description; do not make guesses.

You should also associate the incident with tactics and techniques from the MITRE ATT&CK taxonomy.
Return multiple plausible MITRE ATT&CK tactic chains that explain the attack whenever the logs support more than one reasonable attack progression.
Each tactic chain should represent one coherent possible attack progression supported by the available evidence.
The tactic chains should differ in a meaningful way, such as attacker objective, ordering of tactics, or whether lateral movement occurred, and not merely by dropping one tactic from another chain.
For each tactic chain, assign a probability between 0 and 1 representing how likely that chain is relative to the other returned chains.

Only include tactic chains that are supported by the logs and system description.
Do not invent unsupported attacker behavior.
For incident cases, prefer returning 2 to 3 tactic chains when there is credible ambiguity in the attack progression.
Return a single tactic chain with probability 1.0 only when alternative chains would be speculative or unsupported.

You should also identify entities involved in the incident.

Return a JSON object with five fields:
'Incident',
'Incident description',
'MITRE ATT&CK Tactic Chains',
'MITRE ATT&CK Techniques',
and 'Entities'.

'Incident' should be a string that is either 'Yes' or 'No'.

'Incident description' should be a string with a concise summary of the incident and explanation of why the logs/system description indicate that there is an incident.

'MITRE ATT&CK Tactic Chains' should be an array of JSON objects.
Each object should contain exactly two fields:
- 'chain': an array of strings, where each string is a MITRE ATT&CK tactic
- 'probability': a number between 0 and 1

Return up to 3 of the most plausible tactic chains supported by the logs and system description.
Return at least 2 tactic-chain objects whenever the evidence supports multiple plausible interpretations of the attack progression.
Sort the tactic chains by probability in descending order.
The probabilities should sum to 1 across all returned tactic chains.
Each item in 'MITRE ATT&CK Tactic Chains' must be an object with exactly two keys:
- 'chain'
- 'probability'
Do not output 'MITRE ATT&CK Tactic Chains' as an array of strings.
Do not output a single flat list of tactics.
Return exactly one tactic-chain object only when the evidence clearly supports just one non-speculative progression.

'MITRE ATT&CK Techniques' should be an array of strings, each of which corresponds to one technique used by the attacker in the incident.

'Entities' should be a JSON object with three properties:
'Attacker',
'System',
and 'Targeted'.

'Attacker' should be an array of strings, each of which is either an IP or a hostname that is related to the attacker/adversary.
'System' should be an array of strings, each of which is either an IP or a hostname that corresponds to some component in the system.
'Targeted' should be an array of strings, each of which is either an IP or a hostname that corresponds to some component in the system that is under attack.

If the 'Incident' field is set to 'No', then:
- 'Incident description' should be 'No incident can be inferred from the logs because they contain no substantial information.'
- 'MITRE ATT&CK Tactic Chains' should be an empty array
- 'MITRE ATT&CK Techniques' should be an empty array
- 'Entities' should be an empty JSON object

Example output format:
{{
  "Incident": "Yes",
  "Incident description": "Example incident summary.",
  "MITRE ATT&CK Tactic Chains": [
    {{
      "chain": ["Credential Access", "Initial Access"],
      "probability": 0.72
    }},
    {{
      "chain": ["Credential Access"],
      "probability": 0.28
    }}
  ],
  "MITRE ATT&CK Techniques": [
    "T1110.001 Brute Force: Password Guessing"
  ],
  "Entities": {{
    "Attacker": ["192.168.5.44"],
    "System": ["10.0.30.10", "ad01.hospital.local"],
    "Targeted": ["10.0.30.10", "ad01.hospital.local"]
  }}
}}

Return only the JSON with the above five fields, nothing else.

### Response:
<think>"""


def load_model_and_tokenizer(model_path: str, dtype: torch.dtype) -> tuple[AutoTokenizer, AutoModelForCausalLM]:
    adapter_config = Path(model_path) / "adapter_config.json"
    if adapter_config.exists():
        with adapter_config.open("r", encoding="utf-8") as f:
            adapter_meta = json.load(f)
        base_model = adapter_meta.get("base_model_name_or_path")
        if not base_model:
            raise ValueError("adapter_config.json missing base_model_name_or_path")
        tokenizer = AutoTokenizer.from_pretrained(base_model, use_fast=True)
        base = AutoModelForCausalLM.from_pretrained(
            base_model,
            device_map="auto",
            torch_dtype=dtype,
        )
        model = PeftModel.from_pretrained(base, model_path)
    else:
        tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=True)
        model = AutoModelForCausalLM.from_pretrained(
            model_path,
            device_map="auto",
            torch_dtype=dtype,
        )

    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    model.eval()
    return tokenizer, model


def extract_section(text: str, section_name: str, next_sections: list[str]) -> str:
    pattern = rf"### {re.escape(section_name)}:\s*(.*?)(?=\n### (?:{'|'.join(re.escape(s) for s in next_sections)}):|\Z)"
    match = re.search(pattern, text, flags=re.DOTALL)
    if not match:
        raise ValueError(f"Could not extract section '{section_name}' from dataset instruction")
    return match.group(1).strip()


def rebuild_prompt_from_instruction(instruction: str) -> str:
    system_text = extract_section(instruction, "System", ["Logs", "Instruction", "Response"])
    logs_text = extract_section(instruction, "Logs", ["Instruction", "Response"])
    return PROMPT_TEMPLATE.format(system=system_text, logs=logs_text)


def resolve_prompt(args: argparse.Namespace) -> str:
    if args.dataset:
        ds = load_dataset(args.dataset_repo, data_files=args.dataset)
        sample = ds["train"][0]
        instructions = sample["instructions"]
        if not isinstance(instructions, list) or not instructions:
            raise ValueError("Dataset does not contain a non-empty 'instructions' list")

        if args.random_sample:
            idx = random.randrange(len(instructions))
        else:
            idx = args.sample_index

        if idx < 0 or idx >= len(instructions):
            raise IndexError(
                f"sample index {idx} out of range for dataset with {len(instructions)} instructions"
            )
        print(f"Using dataset sample index: {idx}")
        instruction = instructions[idx]
        if args.use_original_dataset_prompt:
            return instruction
        return rebuild_prompt_from_instruction(instruction)
    if args.prompt_file:
        return Path(args.prompt_file).read_text(encoding="utf-8")
    if args.prompt:
        return args.prompt
    return DEFAULT_PROMPT


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Run a saved checkpoint against a single custom incident prompt."
    )
    parser.add_argument(
        "--model",
        required=True,
        help="Path to a LoRA checkpoint directory or a full model directory.",
    )
    parser.add_argument(
        "--dataset",
        default=None,
        help="Optional HF dataset data_files value, e.g. incident_examples.json.",
    )
    parser.add_argument(
        "--dataset-repo",
        default="kimhammar/CSLE-IncidentResponse-V1",
        help="HF dataset repo id used together with --dataset.",
    )
    parser.add_argument(
        "--sample-index",
        type=int,
        default=0,
        help="Instruction index to read from the dataset when --dataset is set.",
    )
    parser.add_argument(
        "--random-sample",
        action="store_true",
        help="Randomly choose one instruction from the dataset when --dataset is set.",
    )
    parser.add_argument(
        "--use-original-dataset-prompt",
        action="store_true",
        help="Use the dataset instruction exactly as stored instead of rebuilding it with the new template.",
    )
    parser.add_argument(
        "--prompt-file",
        default=None,
        help="Optional path to a text file containing the full prompt.",
    )
    parser.add_argument(
        "--prompt",
        default=None,
        help="Optional inline prompt string. Ignored if --prompt-file is provided.",
    )
    parser.add_argument("--max-new-tokens", type=int, default=1024)
    parser.add_argument("--temperature", type=float, default=0.0)
    parser.add_argument("--top-p", type=float, default=1.0)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--dtype",
        choices=("float16", "bfloat16"),
        default="float16",
        help="Model loading dtype.",
    )
    args = parser.parse_args()

    dtype = torch.float16 if args.dtype == "float16" else torch.bfloat16
    random.seed(args.seed)
    prompt = resolve_prompt(args)
    tokenizer, model = load_model_and_tokenizer(args.model, dtype=dtype)

    inputs = tokenizer(prompt, return_tensors="pt")
    inputs = {k: v.to(model.device) for k, v in inputs.items()}

    with torch.no_grad():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=args.max_new_tokens,
            do_sample=args.temperature > 0.0,
            temperature=args.temperature,
            top_p=args.top_p,
            pad_token_id=tokenizer.pad_token_id,
        )

    full_text = tokenizer.decode(output_ids[0], skip_special_tokens=True)
    generated_text = full_text[len(prompt):] if full_text.startswith(prompt) else full_text

    print("=== Prompt ===")
    print(prompt)
    print("\n=== Model Output ===")
    print(generated_text.strip())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
