"""High-level action providers for the recovery loop."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Protocol

from llm_ir_dt.recovery_loop.high_level_actions import (
    deduplicate_actions,
    parse_high_level_action,
)
from llm_ir_dt.recovery_loop.schemas import (
    HighLevelAction,
    RECOVERY_STATE_FIELDS,
    RecoveryState,
)


ACTION_PROMPT_TEMPLATE = (
    "Below is a system description, a sequence of network logs (e.g., from an intrusion detection system), "
    "a description of a cybersecurity incident, the current state of the recovery from the incident, "
    "a prioritized target server that is most likely under attack, "
    "a list of previously executed recovery actions, "
    "and an instruction that describes a task.\n"
    "Write a response that appropriately completes the request.\nBefore generating the response, "
    "think carefully about the system, the logs, and the instruction, then create a step-by-step "
    "chain of thoughts to ensure a logical and accurate response.\n\n"
    "### System:\n{}\n\n"
    "### Logs:\n{}\n\n"
    "###Incident:\n{}\n\n"
    "### State:\n{}\n"
    "The meaning of the state fields are as follows.\n"
    "is_attack_contained: Has the immediate threat been stopped from spreading?\n"
    "is_knowledge_sufficient: Have we gathered enough data to effectively contain and eradicate the attack?\n"
    "are_forensics_preserved: Has evidence been captured and stored in a forensically sound manner?\n"
    "is_eradicated: Is the adversary completely removed from the system?\n"
    "is_hardened: Has the root cause of the attack been remediated? i.e., are future attacks of the same "
    "type prevented?\n"
    "is_recovered: Are primary services restored for users?\n\n"
    "### Prioritized target server:\n{}\n\n"
    "### Previous recovery actions:\n{}\n\n"
    "### Instruction:\n"
    "You are a security operator with advanced knowledge in cybersecurity "
    "and IT systems. You have been given information about a security incident and should"
    " generate the next suitable action for recovering the prioritized target server from the incident. "
    "Your suggested action should be based on the logs, the system description only, the current state, and the "
    "previous recovery actions.\n"
    "The prioritized target server is the asset most frequently identified as targeted by repeated incident "
    "model generations. Focus recovery on that server first rather than recovering every system globally. "
    "Only include other hosts, gateway controls, or network devices when they are necessary to contain, "
    "investigate, eradicate, harden, or restore the prioritized target server.\n"
    "Make sure that the suggested recovery action is consistent with the system description and the logs and that "
    "you do not repeat any action that has already been performed.\n"
    "The goal when selecting the recovery action is to change the state so that one of the state-properties that "
    "is currently 'false' becomes 'true' for the prioritized target server. The ideal recovery action sequence is: "
    "1. contain the attack affecting the target server 2. gather information about the target server compromise "
    "3. preserve evidence from the target server and directly relevant infrastructure "
    "4. eradicate the attacker from the target server 5. harden the target server and its exposed attack path "
    "6. recover the target server's operational services.\n"
    "When selecting the recovery action, make sure that it is concrete and actionable and minimizes unnecessary "
    "service disruptions. Do not propose broad full-environment rebuilds unless the logs show that the target "
    "server cannot be safely recovered in place. "
    "Vague or unnecessary actions will not change the state and should be avoided.\n"
    "Return a JSON object with two properties: 'Action' and 'Explanation', both of which should be strings.\n"
    "The property 'Action' should be a string that concisely describes the concrete recovery action.\n"
    "The property 'Explanation' should be a string that concisely explains why you selected the recovery action "
    "and motivates why the action is needed.\n\n"
    "### Response:\n<think>"
)


class ActionProvider(Protocol):
    """Interface for candidate high-level action generation."""

    def candidates(
        self,
        state: RecoveryState,
        history: list[HighLevelAction],
        limit: int,
    ) -> list[HighLevelAction]:
        """Return candidate high-level actions for a planning state."""


class MockServerSSHActionProvider:
    """
    Temporary high-level action provider for smoke tests.

    Production experiments should use ``LocalModelActionProvider`` so candidate
    actions are generated by the A100-backed fine-tuned model.
    """

    def candidates(
        self,
        state: RecoveryState,
        history: list[HighLevelAction],
        limit: int,
    ) -> list[HighLevelAction]:
        del history
        actions: list[HighLevelAction]
        if not state.get("is_attack_contained", False):
            actions = [
                HighLevelAction("Block attacker traffic from 10.0.1.11 to 10.0.2.11 at the gateway."),
                HighLevelAction("Collect SSH server logs and account information for investigation."),
                HighLevelAction("Restart the SSH service on the target server."),
            ]
        elif not state.get("is_knowledge_sufficient", False):
            actions = [
                HighLevelAction("Collect SSH server logs and account information for investigation."),
                HighLevelAction("Preserve forensic evidence from the SSH server."),
                HighLevelAction("Disable weak SSH password authentication."),
            ]
        elif not state.get("are_forensics_preserved", False):
            actions = [
                HighLevelAction("Preserve forensic evidence from the SSH server."),
                HighLevelAction("Eradicate attacker access from the SSH server."),
                HighLevelAction("Disable weak SSH password authentication."),
            ]
        elif not state.get("is_eradicated", False):
            actions = [
                HighLevelAction("Eradicate attacker access from the SSH server."),
                HighLevelAction("Disable weak SSH password authentication."),
                HighLevelAction("Recover the SSH service health."),
            ]
        elif not state.get("is_hardened", False):
            actions = [
                HighLevelAction("Disable weak SSH password authentication and root login."),
                HighLevelAction("Recover the SSH service health."),
                HighLevelAction("Collect SSH server logs and account information for investigation."),
            ]
        else:
            actions = [
                HighLevelAction("Recover the SSH service health."),
                HighLevelAction("Preserve forensic evidence from the SSH server."),
                HighLevelAction("Block attacker traffic from 10.0.1.11 to 10.0.2.11 at the gateway."),
            ]
        return deduplicate_actions(actions)[:limit]


class LocalModelActionProvider:
    """
    A100-backed local LoRA/full-model candidate action provider.

    This mirrors the candidate sampling logic in
    ``examples/planning_simulation_qwen_lora_DTserver.py``:
    build an action prompt from context, current state, target server, and
    previous actions; sample until ``limit`` unique actions are collected.
    """

    def __init__(
        self,
        *,
        adapter_path: str,
        context: dict[str, str],
        base_model: str | None = None,
        device_map: str = "auto",
        torch_dtype: str = "float16",
        max_new_tokens: int = 500,
        temperature: float = 0.6,
        top_p: float = 0.9,
        max_attempt_multiplier: int = 3,
    ) -> None:
        self.adapter_path = adapter_path
        self.context = context
        self.base_model = base_model
        self.device_map = device_map
        self.torch_dtype = torch_dtype
        self.max_new_tokens = max_new_tokens
        self.temperature = temperature
        self.top_p = top_p
        self.max_attempt_multiplier = max_attempt_multiplier
        self._tokenizer = None
        self._model = None

    def candidates(
        self,
        state: RecoveryState,
        history: list[HighLevelAction],
        limit: int,
    ) -> list[HighLevelAction]:
        tokenizer, model = self._load()
        prompt = self._build_prompt(state, history)
        actions: list[HighLevelAction] = []
        max_attempts = max(limit, limit * self.max_attempt_multiplier)

        for _ in range(max_attempts):
            raw_output = self._generate(tokenizer, model, prompt)
            action = parse_high_level_action(raw_output)
            actions = deduplicate_actions(actions + [action])
            if len(actions) >= limit:
                return actions[:limit]
        return actions[:limit]

    def _load(self):
        if self._tokenizer is not None and self._model is not None:
            return self._tokenizer, self._model

        import torch
        from peft import PeftConfig, PeftModel
        from transformers import AutoModelForCausalLM, AutoTokenizer

        dtype = getattr(torch, self.torch_dtype)
        adapter_config = Path(self.adapter_path) / "adapter_config.json"
        if adapter_config.exists():
            peft_cfg = PeftConfig.from_pretrained(self.adapter_path)
            base_name = self.base_model or peft_cfg.base_model_name_or_path
            tokenizer = AutoTokenizer.from_pretrained(base_name, use_fast=True)
            base = AutoModelForCausalLM.from_pretrained(
                base_name,
                device_map=self.device_map,
                torch_dtype=dtype,
            )
            model = PeftModel.from_pretrained(base, self.adapter_path)
        else:
            tokenizer = AutoTokenizer.from_pretrained(self.adapter_path, use_fast=True)
            model = AutoModelForCausalLM.from_pretrained(
                self.adapter_path,
                device_map=self.device_map,
                torch_dtype=dtype,
            )

        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.eos_token
        model.eval()
        self._tokenizer = tokenizer
        self._model = model
        return tokenizer, model

    def _build_prompt(
        self,
        state: RecoveryState,
        history: list[HighLevelAction],
    ) -> str:
        state_json = json.dumps(
            {field: bool(state.get(field, False)) for field in RECOVERY_STATE_FIELDS},
            ensure_ascii=True,
        )
        previous_actions = (
            "\n".join(f"- {item.action}" for item in history).strip()
            if history
            else "None."
        )
        return ACTION_PROMPT_TEMPLATE.format(
            self.context.get("System", "").strip(),
            self.context.get("Logs", "").strip(),
            self.context.get("Incident", "").strip(),
            state_json,
            self.context.get("TargetServer", "").strip(),
            previous_actions,
        ).rstrip()

    def _generate(self, tokenizer, model, prompt: str) -> str:
        import torch

        inputs = tokenizer(prompt, return_tensors="pt")
        inputs = {key: value.to(model.device) for key, value in inputs.items()}
        do_sample = self.temperature > 0.0
        with torch.no_grad():
            output_ids = model.generate(
                **inputs,
                max_new_tokens=self.max_new_tokens,
                do_sample=do_sample,
                temperature=self.temperature if do_sample else None,
                top_p=self.top_p if do_sample else None,
                pad_token_id=tokenizer.pad_token_id,
                eos_token_id=tokenizer.eos_token_id,
            )
        decoded = tokenizer.decode(output_ids[0], skip_special_tokens=True)
        if decoded.startswith(prompt):
            decoded = decoded[len(prompt):]
        return decoded.strip()
