"""
Run the recovery loop using LLM-predicted recovery states.

This entry point is intentionally close to ``run_recovery_loop_mock.py``:
high-level actions are generated by the action provider, command plans are
generated by the command agent, and commands are executed in the Docker digital
twin for timing. The difference is that next-state updates come from the
fine-tuned checkpoint state-prediction prompt instead of ``state_verifier.py``.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from dataclasses import replace
from pathlib import Path
from typing import Any

import torch
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from llm_ir_dt.constants.constants import DIGITAL_TWIN
from llm_ir_dt.recovery_loop.action_provider import (
    LocalModelActionProvider,
    MockServerSSHActionProvider,
)
from llm_ir_dt.recovery_loop.baseline_manager import BaselineManager
from llm_ir_dt.recovery_loop.command_agent import (
    DeepSeekCommandAgent,
    MockCommandAgent,
    OpenAICommandAgent,
)
from llm_ir_dt.recovery_loop.command_safety import CommandSafetyValidator
from llm_ir_dt.recovery_loop.orchestrator import (
    RecoveryLoopConfig,
    RecoveryLoopOrchestrator,
)
from llm_ir_dt.recovery_loop.plan_store import PlanStore
from llm_ir_dt.recovery_loop.recovery_executor import RecoveryExecutor
from llm_ir_dt.recovery_loop.schemas import (
    ActionExecutionResult,
    CandidateEvaluation,
    CommandPlan,
    HighLevelAction,
    RECOVERY_STATE_FIELDS,
    RecoveryState,
    has_regression,
    initial_recovery_state,
    is_terminal_state,
    state_progress,
)
from llm_ir_dt.recovery_loop.state_verifier import StateVerification, StateVerifier


DEFAULT_SYSTEM = (
    "The llm_ir_dt_new digital twin contains a client attacker host "
    "10.0.1.11, a gateway IDS/router, and server_ssh at 10.0.2.11."
)
DEFAULT_LOGS = (
    "Snort observed ICMP reconnaissance and repeated SSH connection attempts "
    "from 10.0.1.11 to 10.0.2.11, including SSH brute-force alerts."
)
DEFAULT_INCIDENT = (
    "The SSH server at 10.0.2.11 is targeted by reconnaissance and SSH "
    "brute-force activity from 10.0.1.11."
)

TARGET_SERVER_IPS = {
    "server_ssh": "10.0.2.11",
    "server_samba": "10.0.2.12",
    "server_shellshock": "10.0.2.13",
    "server_web1": "10.0.2.14",
    "server_web2": "10.0.2.15",
}

STATE_PROMPT_TEMPLATE = (
    "Below is a system description, a sequence of network logs (e.g., from an intrusion detection system), "
    "a description of a cybersecurity incident, the current state of the recovery from the incident, "
    "a proposed recovery action, and an instruction that describes a task.\n"
    "Write a response that appropriately completes the request.\nBefore generating the response, "
    "think carefully about the system, the logs, and the instruction, then create a step-by-step "
    "chain of thoughts to ensure a logical and accurate response.\n\n"
    "### System:\n{}\n\n"
    "### Logs:\n{}\n\n"
    "### Incident:\n{}\n\n"
    "### State:\n{}\n"
    "The meaning of the state fields are as follows.\n"
    "is_attack_contained: Has the immediate threat been stopped from spreading?\n"
    "is_knowledge_sufficient: Have we gathered enough data to effectively contain and eradicate the attack?\n"
    "are_forensics_preserved: Has evidence been captured and stored in a forensically sound manner?\n"
    "is_eradicated: Is the adversary completely removed from the system?\n"
    "is_hardened: Has the root cause of the attack been remediated? i.e., are future attacks of the same "
    "type prevented?\n"
    "is_recovered: Are primary services restored for users?\n\n"
    "### Recovery action:\n{}\n\n"
    "### Instruction:\n"
    "You are a security operator with advanced knowledge in cybersecurity "
    "and IT systems.\nYou have been given information about a security incident, the state of recovery from "
    "the incident, "
    "and a recovery action.\nYour task is to predict what the next state of the recovery will be after applying "
    "the recovery action.\n"
    "For example, if the given recovery action effectively contains the attack and 'is_attack_contained' is "
    "'false' in the "
    "current state, then the next state should have 'is_attack_contained' set to 'true'.\nSimilarly, if "
    "'is_recovered' is 'false' "
    "in the current state and the given recovery action effectively recovers operational services of the system,"
    " then the next state "
    "should have 'is_recovered' set to 'true', etc.\nIt is also possible that multiple state properties change "
    "values from false to true. "
    "It is also possible that the state remains the same, i.e., no property changes.\nIt is important that the "
    "state only changes if the "
    "action is effective in achieving one of the recovery goals: containment, information gathering, preserving "
    "evidence, eradication, "
    "hardening, or recovery.\nA state variable can only change from 'false' to 'true', it cannot be changed from "
    "'true' to 'false'.\n"
    "Return a JSON object that defines the next state and contains the Boolean fields 'is_attack_contained', "
    "'is_knowledge_sufficient', 'are_forensics_preserved', 'is_eradicated', 'is_hardened', 'is_recovered'.\n\n"
    "### Response:\n<think>"
)


def read_text_arg(inline_value: str | None, file_value: str | None, default_value: str) -> str:
    """Read an inline/file/default text argument."""
    if file_value:
        return Path(file_value).expanduser().read_text(encoding="utf-8").strip()
    if inline_value:
        return inline_value.strip()
    return default_value


def extract_json_object(text: str) -> dict[str, Any] | None:
    decoder = json.JSONDecoder()
    for match in __import__("re").finditer(r"\{", text):
        try:
            obj, _ = decoder.raw_decode(text[match.start():])
        except json.JSONDecodeError:
            continue
        if isinstance(obj, dict):
            return obj
    return None


def normalize_llm_state(current_state: RecoveryState, predicted: dict[str, Any] | None) -> RecoveryState:
    """Normalize an LLM output and enforce monotonic false-to-true state changes."""
    next_state: RecoveryState = {}
    for field in RECOVERY_STATE_FIELDS:
        current_value = bool(current_state.get(field, False))
        predicted_value = bool(predicted.get(field, current_value)) if predicted else current_value
        next_state[field] = current_value or predicted_value
    return next_state


class NoopStateVerifier(StateVerifier):
    """Verifier stub used only to satisfy BaselineManager's interface."""

    def verify(self) -> StateVerification:
        return StateVerification(state=initial_recovery_state(), evidence={})


class LLMStatePredictor:
    """Checkpoint-backed state predictor using the DT state prompt template."""

    def __init__(
        self,
        *,
        checkpoint_path: str,
        context: dict[str, str],
        base_model: str | None = None,
        device_map: str = "auto",
        torch_dtype: str = "float16",
        max_new_tokens: int = 1200,
        temperature: float = 0.0,
        top_p: float = 0.9,
        print_prompts: bool = False,
        omit_logs_when_printing: bool = False,
        shared_model_loader: Any | None = None,
    ) -> None:
        self.checkpoint_path = checkpoint_path
        self.context = context
        self.base_model = base_model
        self.device_map = device_map
        self.torch_dtype = torch_dtype
        self.max_new_tokens = max_new_tokens
        self.temperature = temperature
        self.top_p = top_p
        self.print_prompts = print_prompts
        self.omit_logs_when_printing = omit_logs_when_printing
        self.shared_model_loader = shared_model_loader
        self._tokenizer = None
        self._model = None

    def predict(self, state: RecoveryState, action: HighLevelAction) -> tuple[RecoveryState, str, dict[str, Any] | None]:
        tokenizer, model = self._load()
        prompt = self._build_prompt(state, action)
        if self.print_prompts:
            print("\n===== LLM STATE PROMPT =====")
            print(self._prompt_for_printing(prompt))
            print("===== END LLM STATE PROMPT =====\n")

        inputs = tokenizer(prompt, return_tensors="pt")
        inputs = {key: value.to(model.device) for key, value in inputs.items()}
        do_sample = self.temperature > 0.0
        with torch.no_grad():
            output_ids = model.generate(
                **inputs,
                max_new_tokens=self.max_new_tokens,
                do_sample=do_sample,
                temperature=self.temperature if do_sample else None,
                top_p=self.top_p if do_sample else None,
                pad_token_id=tokenizer.pad_token_id,
                eos_token_id=tokenizer.eos_token_id,
            )

        decoded = tokenizer.decode(output_ids[0], skip_special_tokens=True)
        if decoded.startswith(prompt):
            decoded = decoded[len(prompt):]
        raw_output = decoded.strip()
        parsed = extract_json_object(raw_output)
        return normalize_llm_state(state, parsed), raw_output, parsed

    def _load(self):
        if self._tokenizer is not None and self._model is not None:
            return self._tokenizer, self._model
        if self.shared_model_loader is not None:
            self._tokenizer, self._model = self.shared_model_loader()
            return self._tokenizer, self._model

        dtype = getattr(torch, self.torch_dtype)
        adapter_config_path = Path(self.checkpoint_path) / "adapter_config.json"
        if adapter_config_path.exists():
            adapter_meta = json.loads(adapter_config_path.read_text(encoding="utf-8"))
            base_model_name = self.base_model or str(adapter_meta["base_model_name_or_path"])
            tokenizer = AutoTokenizer.from_pretrained(base_model_name, use_fast=True)
            base_model = AutoModelForCausalLM.from_pretrained(
                base_model_name,
                device_map=self.device_map,
                torch_dtype=dtype,
            )
            model = PeftModel.from_pretrained(base_model, self.checkpoint_path)
        else:
            tokenizer = AutoTokenizer.from_pretrained(self.checkpoint_path, use_fast=True)
            model = AutoModelForCausalLM.from_pretrained(
                self.checkpoint_path,
                device_map=self.device_map,
                torch_dtype=dtype,
            )

        if tokenizer.pad_token is None:
            tokenizer.pad_token = tokenizer.eos_token
        model.eval()
        self._tokenizer = tokenizer
        self._model = model
        return tokenizer, model

    def _build_prompt(self, state: RecoveryState, action: HighLevelAction) -> str:
        state_text = json.dumps(
            {field: bool(state.get(field, False)) for field in RECOVERY_STATE_FIELDS},
            indent=2,
            ensure_ascii=True,
        )
        return STATE_PROMPT_TEMPLATE.format(
            self.context.get("System", "").strip(),
            self.context.get("Logs", "").strip(),
            self.context.get("Incident", "").strip(),
            state_text,
            action.action.strip(),
        ).rstrip()

    def _prompt_for_printing(self, prompt: str) -> str:
        if not self.omit_logs_when_printing:
            return prompt
        logs_text = self.context.get("Logs", "").strip()
        placeholder = (
            "[LOGS OMITTED FROM PRINTED PROMPT: "
            f"{len(logs_text)} characters, {len(logs_text.splitlines())} lines]"
        )
        return prompt.replace(
            f"### Logs:\n{logs_text}\n\n",
            f"### Logs:\n{placeholder}\n\n",
        )


class LLMStateRecoveryLoopOrchestrator(RecoveryLoopOrchestrator):
    """Recovery loop that uses an LLM state predictor instead of state_verifier."""

    def __init__(self, *, state_predictor: LLMStatePredictor, **kwargs: Any) -> None:
        super().__init__(**kwargs)
        self.state_predictor = state_predictor

    def run(self) -> list[CandidateEvaluation]:
        self.plan_store.write_context(self.context)
        selected: list[CandidateEvaluation] = []
        state = initial_recovery_state()

        for step in range(1, self.config.max_plan_steps + 1):
            if is_terminal_state(state):
                break
            candidates = self.action_provider.candidates(
                state,
                self.history_actions,
                self.config.num_candidates,
            )
            evaluations = []
            for idx, candidate in enumerate(candidates, start=1):
                for rollout_idx in range(1, self.config.num_rollouts + 1):
                    evaluations.append(
                        self.evaluate_candidate(
                            step,
                            idx,
                            state,
                            candidate,
                            rollout_index=rollout_idx,
                            rollout_count=self.config.num_rollouts,
                        )
                    )
            for evaluation in evaluations:
                self.plan_store.save_candidate_evaluation(evaluation)

            best = self._select_best_candidate(evaluations)
            if best is None:
                break
            selected.append(best)

            first_result = best.action_results[0] if best.action_results else None
            if first_result is None or best.first_action_plan is None:
                break
            plan = best.first_action_plan
            self.selected_plans.append(plan)
            self.history_actions.append(best.high_level_action)
            self.plan_store.save_selected_plan(step=step, plan=plan, evaluation=best)
            state = dict(first_result.state_after or best.state_after)

        return selected

    def _select_best_candidate(
        self,
        evaluations: list[CandidateEvaluation],
    ) -> CandidateEvaluation | None:
        grouped: dict[int, list[CandidateEvaluation]] = {}
        for evaluation in evaluations:
            grouped.setdefault(evaluation.candidate_index, []).append(evaluation)

        scored: list[tuple[float, float, float, CandidateEvaluation]] = []
        for samples in grouped.values():
            if len(samples) != self.config.num_rollouts:
                continue
            valid_samples = [sample for sample in samples if sample.valid]
            if not valid_samples:
                continue

            terminal_ratio = sum(
                1 for sample in valid_samples if is_terminal_state(sample.state_after)
            ) / len(samples)
            avg_time = (
                sum(sample.rollout_total_time_seconds for sample in valid_samples)
                / len(valid_samples)
            )
            avg_progress = sum(
                state_progress(sample.state_before, sample.state_after)
                for sample in valid_samples
            ) / len(valid_samples)
            representative = min(
                valid_samples,
                key=lambda item: item.rollout_total_time_seconds,
            )
            scored.append(
                (
                    terminal_ratio,
                    avg_time,
                    avg_progress,
                    replace(representative, rollout_total_time_seconds=avg_time),
                )
            )

        if not scored:
            return None
        return min(scored, key=lambda item: (-item[0], item[1], -item[2]))[3]

    def evaluate_candidate(
        self,
        step: int,
        candidate_index: int,
        state: RecoveryState,
        candidate: HighLevelAction,
        rollout_index: int = 1,
        rollout_count: int = 1,
    ) -> CandidateEvaluation:
        wall_start = time.perf_counter()
        _, baseline_time = self.baseline_manager.restore(self.selected_plans)

        action_results: list[ActionExecutionResult] = []
        rollout_state = dict(state)
        next_action = candidate
        first_action_plan: CommandPlan | None = None
        rollout_time = 0.0
        invalid_reason = ""

        for depth in range(self.config.max_rollout_depth):
            del depth
            before = dict(rollout_state)
            try:
                plan = self._plan_for_action(next_action, rollout_state)
                if first_action_plan is None:
                    first_action_plan = plan
                self.safety.validate_plan(plan)
                exec_result = self.executor.execute_plan(plan, state_before=before)
                after, raw_state_output, parsed_state = self.state_predictor.predict(
                    before,
                    next_action,
                )
            except Exception as exc:
                invalid_reason = f"{type(exc).__name__}: {exc}"
                break

            exec_result = ActionExecutionResult(
                high_level_action=exec_result.high_level_action,
                high_level_action_explanation=exec_result.high_level_action_explanation,
                success=exec_result.success,
                action_execution_time_seconds=exec_result.action_execution_time_seconds,
                action_verification_time_seconds=exec_result.action_verification_time_seconds,
                action_total_time_seconds=exec_result.action_total_time_seconds,
                command_results=exec_result.command_results,
                verification_results=exec_result.verification_results,
                state_before=before,
                state_after=after,
            )
            action_results.append(exec_result)
            rollout_time += exec_result.action_total_time_seconds
            self._save_llm_state_prediction(
                step=step,
                candidate_index=candidate_index,
                rollout_index=rollout_index,
                action=next_action,
                state_before=before,
                raw_output=raw_state_output,
                parsed_state=parsed_state,
                state_after=after,
            )

            if not exec_result.success:
                invalid_reason = "command execution failed"
                break
            if has_regression(before, after):
                invalid_reason = "state regression detected"
                break
            rollout_state = after
            if is_terminal_state(rollout_state):
                break
            rollout_candidates = self.action_provider.candidates(
                rollout_state,
                self.history_actions + [next_action],
                1,
            )
            if not rollout_candidates:
                invalid_reason = "no rollout action generated"
                break
            next_action = rollout_candidates[0]

        progress = state_progress(state, rollout_state)
        success = bool(action_results) and all(result.success for result in action_results)
        valid = success and progress > 0 and not invalid_reason
        if not valid and not invalid_reason:
            invalid_reason = "candidate did not improve LLM-predicted recovery state"

        return CandidateEvaluation(
            step=step,
            candidate_index=candidate_index,
            server=self.config.server,
            server_ip=self.config.server_ip,
            high_level_action=candidate,
            success=success,
            valid=valid,
            state_before=state,
            state_after=rollout_state,
            rollout_total_time_seconds=rollout_time,
            baseline_restore_time_seconds=baseline_time,
            wall_clock_time_seconds=time.perf_counter() - wall_start,
            action_results=tuple(action_results),
            first_action_plan=first_action_plan,
            invalid_reason=invalid_reason,
            rollout_index=rollout_index,
            rollout_count=rollout_count,
        )

    def _save_llm_state_prediction(
        self,
        *,
        step: int,
        candidate_index: int,
        rollout_index: int,
        action: HighLevelAction,
        state_before: RecoveryState,
        raw_output: str,
        parsed_state: dict[str, Any] | None,
        state_after: RecoveryState,
    ) -> None:
        state_dir = self.plan_store.run_dir / "llm_state_predictions"
        state_dir.mkdir(parents=True, exist_ok=True)
        path = state_dir / (
            f"step_{step:03d}_candidate_{candidate_index:03d}_"
            f"rollout_{rollout_index:03d}.json"
        )
        payload = {
            "step": step,
            "candidate_index": candidate_index,
            "rollout_index": rollout_index,
            "action": action.action,
            "action_explanation": action.explanation,
            "state_before": state_before,
            "raw_output": raw_output,
            "parsed_state": parsed_state,
            "state_after": state_after,
        }
        path.write_text(json.dumps(payload, indent=2, ensure_ascii=False), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Run command-agent recovery loop with LLM-predicted state updates."
    )
    parser.add_argument(
        "--server",
        choices=tuple(TARGET_SERVER_IPS),
        default="server_ssh",
        help="Prioritized target server to recover.",
    )
    parser.add_argument("--server-ip", default=None)
    parser.add_argument("--attacker-ip", default="10.0.1.11")
    parser.add_argument("--num-candidates", type=int, default=3)
    parser.add_argument("--num-rollouts", type=int, default=1)
    parser.add_argument("--max-plan-steps", type=int, default=6)
    parser.add_argument("--max-rollout-depth", type=int, default=2)
    parser.add_argument(
        "--action-provider",
        choices=("mock", "local-model"),
        default="mock",
    )
    parser.add_argument("--adapter", default=None)
    parser.add_argument("--base-model", default=None)
    parser.add_argument("--device-map", default="auto")
    parser.add_argument("--torch-dtype", default="float16")
    parser.add_argument("--action-max-new-tokens", type=int, default=500)
    parser.add_argument("--action-temperature", type=float, default=0.6)
    parser.add_argument("--action-top-p", type=float, default=0.9)
    parser.add_argument(
        "--command-agent",
        choices=("mock", "openai", "deepseek"),
        default="mock",
    )
    parser.add_argument("--openai-model", default="gpt-5.5")
    parser.add_argument("--openai-api-key-env", default="OPENAI_API_KEY")
    parser.add_argument("--openai-base-url", default="https://api.openai.com/v1")
    parser.add_argument("--openai-timeout-seconds", type=int, default=120)
    parser.add_argument("--deepseek-model", default="deepseek-v4-pro")
    parser.add_argument("--deepseek-api-key-env", default="DEEPSEEK_API_KEY")
    parser.add_argument("--deepseek-base-url", default="https://api.deepseek.com")
    parser.add_argument("--deepseek-timeout-seconds", type=int, default=120)
    parser.add_argument("--deepseek-max-tokens", type=int, default=4096)
    parser.add_argument("--system", default=None)
    parser.add_argument("--logs", default=None)
    parser.add_argument("--incident", default=None)
    parser.add_argument("--system-file", default=None)
    parser.add_argument("--logs-file", default=None)
    parser.add_argument("--incident-file", default=None)
    parser.add_argument("--dt-context-file", default=None)
    parser.add_argument(
        "--attack-script",
        default="run_attack.py",
        help="Attack script to run after each baseline restore.",
    )
    parser.add_argument(
        "--attack-arg",
        action="append",
        default=[],
        help=(
            "Argument passed to the attack script. Repeat for multiple args, "
            "for example: --attack-script run_attack_alt_pivot.py "
            "--attack-arg --pivot --attack-arg server_shellshock"
        ),
    )
    parser.add_argument("--wait-seconds", type=int, default=15)
    parser.add_argument("--rebuild-images", action="store_true")
    parser.add_argument(
        "--artifacts-dir",
        default=str(ROOT / "artifacts" / "recovery_loop_llm_state"),
    )
    parser.add_argument(
        "--state-checkpoint",
        default=None,
        help="Checkpoint for LLM state prediction. Defaults to --adapter.",
    )
    parser.add_argument("--state-base-model", default=None)
    parser.add_argument("--state-max-new-tokens", type=int, default=1200)
    parser.add_argument("--state-temperature", type=float, default=0.0)
    parser.add_argument("--state-top-p", type=float, default=0.9)
    parser.add_argument("--print-state-prompts", action="store_true")
    parser.add_argument("--omit-logs-when-printing", action="store_true")
    args = parser.parse_args()

    server_ip = args.server_ip or TARGET_SERVER_IPS[args.server]
    context = {
        "System": read_text_arg(args.system, args.system_file, DEFAULT_SYSTEM),
        "Logs": read_text_arg(args.logs, args.logs_file, DEFAULT_LOGS),
        "Incident": read_text_arg(args.incident, args.incident_file, DEFAULT_INCIDENT),
        "TargetServer": f"{args.server} / {server_ip}",
    }
    dt_context = (
        Path(args.dt_context_file).expanduser().read_text(encoding="utf-8").strip()
        if args.dt_context_file
        else ""
    )

    if args.action_provider == "local-model":
        if not args.adapter:
            raise SystemExit("--adapter is required with --action-provider local-model")
        action_provider = LocalModelActionProvider(
            adapter_path=args.adapter,
            base_model=args.base_model,
            context=context,
            device_map=args.device_map,
            torch_dtype=args.torch_dtype,
            max_new_tokens=args.action_max_new_tokens,
            temperature=args.action_temperature,
            top_p=args.action_top_p,
        )
    else:
        action_provider = MockServerSSHActionProvider()

    state_checkpoint = args.state_checkpoint or args.adapter
    if not state_checkpoint:
        raise SystemExit("--state-checkpoint or --adapter is required for LLM state prediction")

    shared_model_loader = None
    if (
        args.action_provider == "local-model"
        and state_checkpoint == args.adapter
        and isinstance(action_provider, LocalModelActionProvider)
    ):
        shared_model_loader = action_provider._load
        print("Using shared local model instance for action generation and state prediction.")

    state_predictor = LLMStatePredictor(
        checkpoint_path=state_checkpoint,
        context=context,
        base_model=args.state_base_model or args.base_model,
        device_map=args.device_map,
        torch_dtype=args.torch_dtype,
        max_new_tokens=args.state_max_new_tokens,
        temperature=args.state_temperature,
        top_p=args.state_top_p,
        print_prompts=args.print_state_prompts,
        omit_logs_when_printing=args.omit_logs_when_printing,
        shared_model_loader=shared_model_loader,
    )

    if args.command_agent == "openai":
        command_agent = OpenAICommandAgent(
            model=args.openai_model,
            api_key_env=args.openai_api_key_env,
            base_url=args.openai_base_url,
            timeout_seconds=args.openai_timeout_seconds,
        )
    elif args.command_agent == "deepseek":
        command_agent = DeepSeekCommandAgent(
            model=args.deepseek_model,
            api_key_env=args.deepseek_api_key_env,
            base_url=args.deepseek_base_url,
            timeout_seconds=args.deepseek_timeout_seconds,
            max_tokens=args.deepseek_max_tokens,
        )
    else:
        command_agent = MockCommandAgent()

    executor = RecoveryExecutor()
    baseline = BaselineManager(
        project_root=ROOT,
        executor=executor,
        verifier=NoopStateVerifier(),
        wait_seconds=args.wait_seconds,
        rebuild_images=args.rebuild_images,
        attack_command=[args.attack_script, *args.attack_arg],
    )
    orchestrator = LLMStateRecoveryLoopOrchestrator(
        state_predictor=state_predictor,
        context=context,
        config=RecoveryLoopConfig(
            server=args.server,
            server_ip=server_ip,
            attacker_ip=args.attacker_ip,
            num_candidates=args.num_candidates,
            num_rollouts=args.num_rollouts,
            max_plan_steps=args.max_plan_steps,
            max_rollout_depth=args.max_rollout_depth,
        ),
        command_agent=command_agent,
        action_provider=action_provider,
        safety=CommandSafetyValidator(),
        executor=executor,
        verifier=NoopStateVerifier(),
        baseline_manager=baseline,
        plan_store=PlanStore(args.artifacts_dir),
        dt_context=dt_context,
    )
    selected = orchestrator.run()
    print(f"Selected {len(selected)} actions. Artifacts: {orchestrator.plan_store.run_dir}")
    for item in selected:
        print(
            f"step={item.step} action={item.high_level_action.action} "
            f"rollout_total_time_seconds={item.rollout_total_time_seconds:.3f} "
            f"llm_state_after={item.state_after}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
